//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int CellsForPages {
            get {
                return ((int)(this["CellsForPages"]));
            }
            set {
                this["CellsForPages"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT Empleados.Id_Emp, Empleados.C_R, Empleados.Nombre, Empleados.Gener, Departamento.Nombre AS Dep, Empleados.Dir, Empleados.Telf, Empleados.Movil, Empleados.Email, Empleados.F_Nac, Empleados.Entry, Empleados.Modify, Empleados.Pict, Empleados.Oculto FROM (Empleados INNER JOIN Departamento ON Departamento.Id_Dep = Empleados.Id_Dep) ")]
        public string ConsultaEmp {
            get {
                return ((string)(this["ConsultaEmp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT Productos.Id_Pro, Productos.Code, Productos.Descrip, Categorias.Nombre AS Categoria, Productos.Cost, Productos.Price, Productos.Stock, Proveedores.Nombre AS Proveedor, Productos.Notes, Productos.Entry, Productos.Modify, Productos.Pict, Productos.Oculto FROM ((Productos INNER JOIN Categorias ON Categorias.Id_Cat = Productos.Id_Cat) INNER JOIN Proveedores ON Proveedores.Id_Sup = Productos.Id_Sup)")]
        public string ConsultaInv {
            get {
                return ((string)(this["ConsultaInv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Proveedores")]
        public string ConsultaPro {
            get {
                return ((string)(this["ConsultaPro"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT R_Sesion.Id, Empleados.Nombre AS Empleado, R_Sesion.Entry, R_Sesion.Exit F" +
            "ROM R_Sesion INNER JOIN Empleados ON Empleados.Id_Emp = R_Sesion.Id_Emp")]
        public string ConsultaReg {
            get {
                return ((string)(this["ConsultaReg"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT Ventas.Id_Ven, Productos.Descrip AS Producto, Ventas.Total, Ventas.Stock, " +
            "Empleados.Nombre AS Empleado, Ventas.Fecha FROM ((Ventas INNER JOIN Productos ON" +
            " Ventas.Id_Pro = Productos.Id_Pro) INNER JOIN Empleados ON Empleados.Id_Emp = Ve" +
            "ntas.Id_Emp)")]
        public string ConsultaVen {
            get {
                return ((string)(this["ConsultaVen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Departamento")]
        public string ConsultaDep {
            get {
                return ((string)(this["ConsultaDep"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RecordUser {
            get {
                return ((bool)(this["RecordUser"]));
            }
            set {
                this["RecordUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserSave {
            get {
                return ((string)(this["UserSave"]));
            }
            set {
                this["UserSave"] = value;
            }
        }
    }
}
